#!/usr/bin/env python3
"""Bakes the numbers the browser demo needs into demo/trajectories.js as a
plain JS object literal - no fetch, no server, just open index.html.

    python3 demo/generate_demo_data.py
"""

import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np

import experiments.algorithms as algo_module
import experiments.mads as mads_module
from experiments.algorithms import (
    complete_coordinate_search,
    ordered_coordinate_search,
    opportunistic_coordinate_search,
)
from experiments.blackbox import Blackbox
from experiments.finance_problem import portfolio_neg_sharpe
from experiments.mads import mesh_adaptive_search
from experiments.test_functions import rastrigin, rosenbrock

ALGORITHMS = {
    "Complete": complete_coordinate_search,
    "Ordered": ordered_coordinate_search,
    "Opportunistic": opportunistic_coordinate_search,
    "MADS": mesh_adaptive_search,
}

LANDSCAPE_EVAL_BUDGET = 300
PORTFOLIO_EVAL_BUDGET = 2000
GRID_RES = 90


class TrajectoryWrapper:
    """Same job as experiments.blackbox.Blackbox, but also remembers where
    the incumbent point was every time it improved - the main Blackbox
    class doesn't bother with that since it would be wasteful for the full
    10-d benchmark runs.
    """

    def __init__(self, func):
        self.func = func
        self.eval_count = 0
        self.cpu_time = 0.0
        self.path = []
        self._best_f = None

    def evaluate(self, x):
        t0 = time.perf_counter()
        f_val = float(self.func(x))
        self.cpu_time += time.perf_counter() - t0
        self.eval_count += 1
        if self._best_f is None or f_val < self._best_f:
            self._best_f = f_val
            self.path.append({"evals": self.eval_count, "x": [float(x[0]), float(x[1])], "f": f_val})
        return f_val

    def reset(self):
        self.eval_count = 0
        self.cpu_time = 0.0
        self.path = []
        self._best_f = None


def build_contour(func, grid_res=GRID_RES):
    xs = np.linspace(-1.0, 1.0, grid_res)
    ys = np.linspace(-1.0, 1.0, grid_res)
    z = np.array([[func(np.array([x, y])) for x in xs] for y in ys])
    return xs.tolist(), ys.tolist(), z.tolist()


def build_trajectories(func, x0):
    algo_module.MAX_EVALS = LANDSCAPE_EVAL_BUDGET
    mads_module.MAX_EVALS = LANDSCAPE_EVAL_BUDGET

    trajectories = {}
    for name, algo_fn in ALGORITHMS.items():
        np.random.seed(3)
        wrapper = TrajectoryWrapper(func)
        algo_fn(wrapper, x0)
        trajectories[name] = wrapper.path
    return trajectories


def build_portfolio_curves():
    algo_module.MAX_EVALS = PORTFOLIO_EVAL_BUDGET
    mads_module.MAX_EVALS = PORTFOLIO_EVAL_BUDGET

    x0 = np.zeros(10)
    curves = {}
    for name, algo_fn in ALGORITHMS.items():
        np.random.seed(3)
        blackbox = Blackbox(portfolio_neg_sharpe, record_trace=True)
        algo_fn(blackbox, x0)
        curves[name] = blackbox.trace
    return curves


def main():
    np.random.seed(11)

    functions = {}
    for name, func in [("Rosenbrock", rosenbrock), ("Rastrigin", rastrigin)]:
        x0 = np.random.uniform(-1.0, 1.0, size=2)
        xs, ys, zs = build_contour(func)
        functions[name] = {
            "x": xs,
            "y": ys,
            "z": zs,
            "x0": x0.tolist(),
            "trajectories": build_trajectories(func, x0),
        }

    data = {"functions": functions, "portfolio": build_portfolio_curves()}

    out_path = os.path.join(os.path.dirname(__file__), "trajectories.js")
    with open(out_path, "w") as f:
        f.write("// generated by demo/generate_demo_data.py - don't hand-edit\n")
        f.write("const DEMO_DATA = ")
        json.dump(data, f)
        f.write(";\n")

    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
